#!/usr/bin/env python3
"""Generate `data/building_economy.json` for SLACUM CITY.

Source of truth: `docs/design/03-economy.md` (Round 3; report 98 rulings C-07,
C-16, RR-5, RR-13, RR-16, RR-18).  Nothing is read from disk: doc 03's money
table (s2.2 / s2.13a) and its published `base_tax_by_level` rows are
transcribed verbatim below, every generated column is grown from them by the
s2.3 curve family, and every cell the doc publishes is diffed before a byte is
written.

What this file owns (doc 03 s3.2's contract keys):

    class, build_cost_l1, base_tax_l1, base_tax_by_level,
    upgrade_cost_by_step, capital_value_by_level

Doc 03 s3.2 nominates `data/buildings.json` as the carrier for these keys.  The
shipped `data/buildings.json` is generated by `tools/gen_buildings.py` from doc
02, whose `forbidden_keys` list bans every cost column (report 98 C-07 / C-08),
so the two generators would fight over one file.  The economy columns therefore
ship in their own generated file, keyed by doc 03's archetype ids, with
`doc02_archetype_alias` mapping doc 02's roster onto it.  See MISMATCH below.

Generation contract (doc 03 s2.2 / s2.3):

    base_tax(type, L)        = round( base_tax_l1 x TAX_LEVEL_GROWTH^(L-1) )
    upgrade_cost(type, L->L+1) = round( build_cost_l1 x UPG_COEFF x UPG_GROWTH^(L-1) )
    capital_value(type, L)   = round( build_cost_l1 x V(L) )
    V(L)                     = 1 + (UPG_COEFF/(UPG_GROWTH-1)) x (UPG_GROWTH^(L-1) - 1)

  * `round()` is half-up throughout doc 03 (s2.8's own note), and the
    arithmetic here is `decimal.Decimal` with ROUND_HALF_UP so a tie is a real
    tie and never a binary-float artefact;
  * `V(L)` ships as the 3-dp vector `upgrades.CAPITAL_VALUE_V` in doc 03 s8
    (`[1.000, 2.450, 6.147, 15.576, 39.620]`).  The PUBLISHED capital values are
    generated from that vector, not from the exact closed form -- see
    CAPITAL_VALUE_NOTE, and `published_cell_overrides` in the emitted file;
  * the PUBLISHED `base_tax_by_level` rows are NORMATIVE (report 98 RR-5).
    Where the curve and the published cell disagree the published cell ships and
    the difference is recorded; three cells are affected, all by exactly $1.

Usage:
    python3 tools/gen_building_economy.py [--out-dir DATA_DIR] [--check]

    --check   validate only; do not write.
"""

from __future__ import annotations

import argparse
import os
import sys
from decimal import Decimal as D, ROUND_HALF_UP, getcontext
from typing import Any, Dict, List, Optional

getcontext().prec = 60

LEVELS = 5
## The sixth rung (doc 02 s2.14 / doc 92 s23). Doc 03 s2.2's money table is a
## per-LEVEL ladder on the same two constants, so the sixth rung of the six
## archetypes that grew one is `base_tax_l1 x 2.15^5`, `build_cost_l1 x V(6)` and
## a fifth `upgrade_cost` step `build_cost_l1 x 1.45 x 2.55^4` -- the curve
## extended, not re-fitted. Doc 03's ids, not doc 02's: `highrise_res` is doc
## 02's `high_rise`. `factory` and `highrise_com` have no doc-02 archetype to
## carry a sixth rung FOR, and the civic/utility rows stop at five with their
## doc-02 counterparts.
TOP_LEVELS = 6
SIXTH_LEVEL_ARCHETYPES = ["house", "store", "apartment", "office",
                          "highrise_res", "data_center"]


def levels_of(archetype: str) -> int:
    return TOP_LEVELS if archetype in SIXTH_LEVEL_ARCHETYPES else LEVELS


FAILURES: List[str] = []


def fail(message: str) -> None:
    FAILURES.append(message)


def r(value: D) -> int:
    """doc 03's `round()`: half-up, always (s2.8)."""
    return int(D(value).quantize(D("1"), rounding=ROUND_HALF_UP))


# ==========================================================================
# 1. Curve constants -- doc 03 s2.2 / s2.3 / s8 `tax` + `upgrades`
# ==========================================================================

TAX_LEVEL_GROWTH = D("2.15")
UPG_COEFF = D("1.45")
UPG_GROWTH = D("2.55")

# doc 03 s8 `upgrades.CAPITAL_VALUE_V` -- the published 3-dp vector.
CAPITAL_VALUE_V = [D("1.000"), D("2.450"), D("6.147"), D("15.576"), D("39.620"),
                   D("100.929")]
# V(6) is NEW (doc 92 s23.4) and it is the only cell of the vector this project
# ever placed itself, so it is placed by the rule the other five claim rather
# than by judgement: the closed form gives V(6) = 100.9287528125 exactly, and
# half-up at 3 dp is 100.929. The two earlier cells that disagree with their own
# closed form (V3, V5) are doc 03's and are left exactly as published.

CAPITAL_VALUE_NOTE = (
    "doc 03 s2.3 states BOTH the closed form V(L) = 1 + (UPG_COEFF/(UPG_GROWTH-1))"
    " x (UPG_GROWTH^(L-1) - 1) AND the rounded 3-dp vector CAPITAL_VALUE_V"
    " [1.000, 2.450, 6.147, 15.576, 39.620] that data/economy.json s8 ships. They"
    " disagree at L3 and L5: exact V3 = 6.1475 and V5 = 39.6191187, so a house"
    " generates 7377 / 47543 from the closed form against the 7376 / 47544 doc 03"
    " s2.3 and s3.2 publish (and doc 02 s2.2's payback check recomputes at 7376)."
    " The published cells win, so this generator multiplies by CAPITAL_VALUE_V."
)

# doc 03 s2.2's yield map -- DESCRIPTIVE ONLY (report 98 RR-5). Checked here as
# the same +/-6% drift guard doc 03 s7 test 7 applies, never as an equality.
TAX_YIELD = {
    "residential": D("0.0100"),
    "commercial": D("0.0105"),
    "industrial": D("0.0095"),
    "tech": D("0.0117"),
}
TAX_YIELD_DRIFT_TOLERANCE = D("0.06")


# ==========================================================================
# 2. The money table -- doc 03 s2.2 (build cost + published base_tax rows)
#    and s2.13(a) (the same build costs, restated as the currency ladder)
# ==========================================================================
# `base_tax` rows are the PUBLISHED, NORMATIVE rows (RR-5). Civic and utility
# archetypes have base_tax = 0 at every level (s2.2).

ARCHETYPE_ORDER = [
    "house", "store", "apartment", "office", "factory",
    "highrise_res", "highrise_com", "data_center",
    "construction_yard", "substation", "police_station", "fire_station",
    "water_plant", "power_plant_gas",
]

MONEY_TABLE: Dict[str, Dict[str, Any]] = {
    "house":             {"class": "residential", "build_cost_l1": 1200,
                          "base_tax": [12, 26, 55, 119, 256, 551]},
    "store":             {"class": "commercial", "build_cost_l1": 2600,
                          "base_tax": [26, 56, 120, 258, 556, 1194]},
    "apartment":         {"class": "residential", "build_cost_l1": 7000,
                          "base_tax": [70, 151, 324, 696, 1496, 3216]},
    "office":            {"class": "commercial", "build_cost_l1": 13000,
                          "base_tax": [130, 280, 601, 1292, 2778, 5972]},
    "factory":           {"class": "industrial", "build_cost_l1": 22000,
                          "base_tax": [210, 452, 971, 2087, 4487]},
    "highrise_res":      {"class": "residential", "build_cost_l1": 26000,
                          "base_tax": [260, 559, 1202, 2584, 5555, 11944]},
    "highrise_com":      {"class": "commercial", "build_cost_l1": 40000,
                          "base_tax": [420, 903, 1941, 4174, 8974]},
    "data_center":       {"class": "tech", "build_cost_l1": 180000,
                          "base_tax": [2100, 4515, 9707, 20870, 44871, 96474]},
    "construction_yard": {"class": "civic", "build_cost_l1": 16000,
                          "base_tax": [0, 0, 0, 0, 0]},
    "substation":        {"class": "utility", "build_cost_l1": 15000,
                          "base_tax": [0, 0, 0, 0, 0]},
    "police_station":    {"class": "civic", "build_cost_l1": 18000,
                          "base_tax": [0, 0, 0, 0, 0]},
    "fire_station":      {"class": "civic", "build_cost_l1": 20000,
                          "base_tax": [0, 0, 0, 0, 0]},
    "water_plant":       {"class": "utility", "build_cost_l1": 45000,
                          "base_tax": [0, 0, 0, 0, 0]},
    "power_plant_gas":   {"class": "utility", "build_cost_l1": 60000,
                          "base_tax": [0, 0, 0, 0, 0]},
}

REVENUE_CLASSES = ["residential", "commercial", "industrial", "tech"]

# doc 03 s2.5: grid components are REPLACED, not upgraded, so their repair
# capital is their s2.13(b) build cost at the current level -- which lives in
# data/economy.json `expenses.grid_components`, not in the V(L) ladder below.
GRID_SHELL_ARCHETYPES = {
    "substation": "expenses.grid_components.substation.build_cost",
    "power_plant_gas": "expenses.grid_components.plant_gas.build_cost",
}

# doc 02's MVP roster uses different ids for four archetypes and ships neither
# `factory` nor a commercial high-rise. Recorded here so a doc-02 consumer can
# resolve its archetype id onto a doc-03 money row (MISMATCH, reported).
DOC02_ALIAS = {
    "high_rise": "highrise_res",
    "power_facility": "power_plant_gas",
    "water_facility": "water_plant",
}
DOC02_UNMAPPED = ["factory", "highrise_com"]

MISMATCH_NOTE = (
    "doc 03 s2.2 costs 14 archetypes; doc 02's shipped data/buildings.json costs"
    " 12 and names four of them differently. `high_rise` (doc 02, tax_class"
    " residential) is doc 03's `highrise_res`; `power_facility` is"
    " `power_plant_gas`; `water_facility` is `water_plant`. doc 03's `factory`"
    " (industrial, 22,000) and `highrise_com` (commercial, 40,000) have no doc-02"
    " archetype at all -- their rows ship here because doc 03 s2.2, s2.13(a) and"
    " the s7 test plan are all written against them."
)


# ==========================================================================
# 3. Published cells doc 03 states outside the s2.2 table -- diffed, not copied
# ==========================================================================

PUBLISHED_UPGRADE_STEPS = {
    # doc 03 s2.3 "House example" and s3.2's schema sample.
    # The fifth step is the sixth rung's (doc 92 s23.4): 1,200 x 1.45 x 2.55^4.
    "house": [1740, 4437, 11314, 28852, 73572],
}
PUBLISHED_CAPITAL_VALUES = {
    # doc 03 s3.2's schema sample (and s2.3's "L5 capital value 47,544").
    "house": [1200, 2940, 7376, 18691, 47544, 121115],
}
# Single published capital cells stated elsewhere in the project.
PUBLISHED_CAPITAL_CELLS = [
    # (archetype, level, value, source)
    ("house", 3, 7376, "doc 02 s2.2 payback worked check (1,200 x 6.147)"),
    ("apartment", 3, 43029, "doc 02 s2.6 repair worked example (7,000 x 6.147)"),
]
PUBLISHED_STEP_MULTIPLIERS = [D("1.45"), D("3.6975"), D("9.4286"), D("24.0429"),
                             D("61.3096")]

# doc 03 s2.12 / C-11: the starter anchor the whole pacing model hangs on.
STARTER_ANCHOR_MIX = [("house", 1, 18), ("store", 1, 5), ("apartment", 1, 3), ("office", 1, 1)]
STARTER_ANCHOR_TOTAL = 686


# ==========================================================================
# 4. Generation
# ==========================================================================

def gen_base_tax(base_tax_l1: int, top: int = LEVELS) -> List[int]:
    return [r(D(base_tax_l1) * TAX_LEVEL_GROWTH ** (L - 1)) for L in range(1, top + 1)]


def gen_upgrade_steps(build_cost_l1: int, top: int = LEVELS) -> List[int]:
    return [r(D(build_cost_l1) * UPG_COEFF * UPG_GROWTH ** (L - 1)) for L in range(1, top)]


def gen_capital_values(build_cost_l1: int, top: int = LEVELS) -> List[int]:
    return [r(D(build_cost_l1) * v) for v in CAPITAL_VALUE_V[:top]]


def exact_capital_values(build_cost_l1: int, top: int = LEVELS) -> List[int]:
    coefficient = UPG_COEFF / (UPG_GROWTH - 1)
    return [r(D(build_cost_l1) * (D(1) + coefficient * (UPG_GROWTH ** (L - 1) - 1)))
            for L in range(1, top + 1)]


def build_document() -> Dict[str, Any]:
    archetypes: Dict[str, Any] = {}
    base_tax_overrides: List[Dict[str, Any]] = []
    capital_overrides: List[Dict[str, Any]] = []
    closed_form_deltas: List[int] = []

    # --- step multipliers reproduce doc 03 s2.3's printed vector ------------
    for index, printed in enumerate(PUBLISHED_STEP_MULTIPLIERS):
        actual = UPG_COEFF * UPG_GROWTH ** index
        if abs(actual - printed) > D("0.0001"):
            fail("step multiplier %d: doc 03 prints %s, curve gives %s"
                 % (index + 1, printed, actual))

    for archetype in ARCHETYPE_ORDER:
        row = MONEY_TABLE[archetype]
        cost = int(row["build_cost_l1"])
        published_tax = list(row["base_tax"])
        klass = row["class"]
        top = levels_of(archetype)
        if len(published_tax) != top:
            fail("%s: money table has %d base_tax rows, ladder is %d"
                 % (archetype, len(published_tax), top))
            continue

        generated_tax = gen_base_tax(published_tax[0], top)
        for level in range(1, top + 1):
            generated = generated_tax[level - 1]
            published = published_tax[level - 1]
            if generated == published:
                continue
            if abs(generated - published) > 1:
                fail("%s base_tax L%d: published %d, curve %d (drift > $1)"
                     % (archetype, level, published, generated))
                continue
            base_tax_overrides.append({
                "archetype": archetype, "level": level, "field": "base_tax_by_level",
                "published": published, "from_curve": generated,
                "arithmetic": "%d x 2.15^%d = %s -> half-up %d"
                              % (published_tax[0], level - 1,
                                 str((D(published_tax[0]) * TAX_LEVEL_GROWTH ** (level - 1))
                                     .quantize(D("0.0001"), rounding=ROUND_HALF_UP)), generated),
                "ruling": "report 98 RR-5 -- the published rows are normative; doc 03 s2.2"
                          " flags these three cells and locks them. s7 test 8 carries a"
                          " +/-$1 tolerance on generated cells instead.",
            })

        upgrade_steps = gen_upgrade_steps(cost, top)
        if archetype in PUBLISHED_UPGRADE_STEPS:
            if upgrade_steps != PUBLISHED_UPGRADE_STEPS[archetype]:
                fail("%s upgrade_cost_by_step: published %s, curve %s"
                     % (archetype, PUBLISHED_UPGRADE_STEPS[archetype], upgrade_steps))

        capital_values = gen_capital_values(cost, top)
        exact = exact_capital_values(cost, top)
        for level in range(1, top + 1):
            if capital_values[level - 1] == exact[level - 1]:
                continue
            closed_form_deltas.append(abs(capital_values[level - 1] - exact[level - 1]))
            # Only the cells doc 03 / doc 02 actually PUBLISH are recorded as
            # overrides; the rest of the divergence is the same systematic
            # 3-dp-vector-vs-closed-form effect, summarised in `capital_value_basis`.
            if archetype not in PUBLISHED_CAPITAL_VALUES \
                    and not any(a == archetype and L == level for a, L, _v, _s in PUBLISHED_CAPITAL_CELLS):
                continue
            capital_overrides.append({
                "archetype": archetype, "level": level, "field": "capital_value_by_level",
                "published": capital_values[level - 1], "from_closed_form": exact[level - 1],
                "arithmetic": "%d x V(%d): CAPITAL_VALUE_V %s -> %d, closed form %s -> %d"
                              % (cost, level, CAPITAL_VALUE_V[level - 1],
                                 capital_values[level - 1],
                                 str((D(1) + (UPG_COEFF / (UPG_GROWTH - 1))
                                      * (UPG_GROWTH ** (level - 1) - 1))
                                     .quantize(D("0.0000001"), rounding=ROUND_HALF_UP)),
                                 exact[level - 1]),
                "ruling": "doc 03 s8 ships CAPITAL_VALUE_V as the 3-dp vector and s2.3 / s3.2"
                          " publish the cells it produces; the vector wins.",
            })

        if archetype in PUBLISHED_CAPITAL_VALUES:
            if capital_values != PUBLISHED_CAPITAL_VALUES[archetype]:
                fail("%s capital_value_by_level: published %s, generated %s"
                     % (archetype, PUBLISHED_CAPITAL_VALUES[archetype], capital_values))

        entry: Dict[str, Any] = {
            "class": klass,
            "build_cost_l1": cost,
            "base_tax_l1": published_tax[0],
            "revenue_producing": klass in REVENUE_CLASSES,
            "base_tax_by_level": published_tax,
            "upgrade_cost_by_step": upgrade_steps,
            "capital_value_by_level": capital_values,
        }
        if archetype in GRID_SHELL_ARCHETYPES:
            entry["repair_capital_source"] = GRID_SHELL_ARCHETYPES[archetype]
            entry["_repair_capital_note"] = (
                "doc 03 s2.5: grid components are replaced, not upgraded, so their repair"
                " capital_value is the s2.13(b) build cost at the current level, NOT the"
                " V(L) column above. The V(L) column is kept so the shell still has a"
                " maintenance/demolition basis as a building.")
        archetypes[archetype] = entry

    # --- published single cells --------------------------------------------
    for archetype, level, value, source in PUBLISHED_CAPITAL_CELLS:
        got = archetypes[archetype]["capital_value_by_level"][level - 1]
        if got != value:
            fail("%s capital_value L%d: %s publishes %d, generated %d"
                 % (archetype, level, source, value, got))

    # --- RR-5 drift guard (doc 03 s7 test 7) --------------------------------
    drift_rows = []
    for archetype in ARCHETYPE_ORDER:
        entry = archetypes[archetype]
        if not entry["revenue_producing"]:
            continue
        estimate = D(entry["build_cost_l1"]) * TAX_YIELD[entry["class"]]
        drift = D(entry["base_tax_l1"]) / estimate - 1
        if abs(drift) > TAX_YIELD_DRIFT_TOLERANCE:
            fail("%s yield drift %s exceeds +/-%s" % (archetype, drift, TAX_YIELD_DRIFT_TOLERANCE))
        drift_rows.append({
            "archetype": archetype, "class": entry["class"],
            "build_cost_l1": entry["build_cost_l1"],
            "yield_estimate": r(estimate),
            "published_base_tax_l1": entry["base_tax_l1"],
            "drift": str(drift.quantize(D("0.000001"), rounding=ROUND_HALF_UP)),
        })
    # The negative case doc 03 s7 test 7 / RR-18 names: a mis-classed data_center.
    misclassed = D(180000) * TAX_YIELD["residential"]
    misclassed_drift = D(2100) / misclassed - 1
    if misclassed_drift <= TAX_YIELD_DRIFT_TOLERANCE:
        fail("the drift guard would not catch a residential-classed data_center")

    # --- the $686 starter anchor (doc 03 s2.12 / C-11) ----------------------
    anchor = sum(count * archetypes[archetype]["base_tax_by_level"][level - 1]
                 for archetype, level, count in STARTER_ANCHOR_MIX)
    if anchor != STARTER_ANCHOR_TOTAL:
        fail("starter anchor: doc 03 s2.12 requires %d/gh, rows give %d/gh"
             % (STARTER_ANCHOR_TOTAL, anchor))

    return {
        "schema_version": 1,
        "generated": {
            "generator": "tools/gen_building_economy.py",
            "source_doc": "docs/design/03-economy.md (Round 3; C-07, C-16, RR-5, RR-13, RR-16, RR-18)",
            "owner_doc": "03-economy.md",
            "contract_keys": ["class", "build_cost_l1", "base_tax_l1", "base_tax_by_level",
                              "upgrade_cost_by_step", "capital_value_by_level"],
            "archetype_count": len(ARCHETYPE_ORDER),
            "levels_per_archetype": LEVELS,
            "top_levels_per_archetype": TOP_LEVELS,
            "levels_by_archetype": {a: levels_of(a) for a in ARCHETYPE_ORDER},
            "archetype_order": list(ARCHETYPE_ORDER),
            "curves": {
                "TAX_LEVEL_GROWTH": str(TAX_LEVEL_GROWTH),
                "UPG_COEFF": str(UPG_COEFF),
                "UPG_GROWTH": str(UPG_GROWTH),
                "CAPITAL_VALUE_V": [str(v) for v in CAPITAL_VALUE_V],
                "_v6_note": "V(6) = 100.929 is NEW (doc 92 s23.4): the closed form gives"
                            " 100.9287528125 exactly and half-up at 3 dp is 100.929. It is"
                            " the only cell of this vector the project placed itself, and it"
                            " is placed by the rule the other five claim.",
                "rounding": "half-up, once per cell (doc 03 s2.8)",
            },
            "_file_placement_note": MISMATCH_NOTE,
            "capital_value_basis": {
                "basis": "upgrades.CAPITAL_VALUE_V (doc 03 s8), applied as"
                         " round_half_up(build_cost_l1 x V(L))",
                "cells_differing_from_closed_form": len(closed_form_deltas),
                "max_absolute_difference_dollars": max(closed_form_deltas) if closed_form_deltas else 0,
                "_note": CAPITAL_VALUE_NOTE,
            },
            "_base_tax_note": "base_tax_by_level ships doc 03 s2.2's PUBLISHED rows verbatim"
                              " (report 98 RR-5): they are normative, TAX_YIELD is a derivation"
                              " aid, and the generator diffs rather than replaces them.",
            "starter_anchor": {
                "mix": [{"archetype": a, "level": L, "count": n} for a, L, n in STARTER_ANCHOR_MIX],
                "gross_base_tax_per_hour": anchor,
            },
            "yield_drift_guard": {
                "TAX_YIELD": {k: str(v) for k, v in TAX_YIELD.items()},
                "tolerance": str(TAX_YIELD_DRIFT_TOLERANCE),
                "rows": drift_rows,
                "negative_case": {
                    "archetype": "data_center", "as_class": "residential",
                    "drift": str(misclassed_drift.quantize(D("0.00001"), rounding=ROUND_HALF_UP)),
                    "_note": "report 98 RR-18: 2,100 / (180,000 x 0.0100) - 1 = +0.16667, which"
                             " the +/-6% guard rejects.",
                },
            },
            "published_cell_overrides": base_tax_overrides + capital_overrides,
        },
        "doc02_archetype_alias": DOC02_ALIAS,
        "doc02_unmapped_archetypes": DOC02_UNMAPPED,
        "archetypes": archetypes,
    }


# ==========================================================================
# 5. JSON emitter -- same shape as tools/gen_buildings.py, byte-stable
# ==========================================================================

MAX_INLINE = 460
FORCE_BLOCK = {"archetypes", "generated", "published_cell_overrides", "rows", "curves",
               "yield_drift_guard", "starter_anchor"}
_ESCAPES = {'"': '\\"', "\\": "\\\\", "\n": "\\n", "\t": "\\t", "\r": "\\r"}


def _scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, D):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        raise TypeError("binary floats are not allowed in generated data: %r" % value)
    if isinstance(value, str):
        return '"' + "".join(_ESCAPES.get(c, c) for c in value) + '"'
    raise TypeError("cannot encode %r" % (value,))


def _compact(value: Any) -> str:
    if isinstance(value, dict):
        return "{" + ", ".join('%s: %s' % (_scalar(str(k)), _compact(v))
                               for k, v in value.items()) + "}"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_compact(v) for v in value) + "]"
    return _scalar(value)


def _encode(value: Any, indent: int, key: Optional[str]) -> str:
    pad = "  " * indent
    inner = "  " * (indent + 1)
    if isinstance(value, (dict, list, tuple)):
        if not value:
            return "{}" if isinstance(value, dict) else "[]"
        compact = _compact(value)
        if key not in FORCE_BLOCK and len(compact) + len(pad) <= MAX_INLINE:
            return compact
        if isinstance(value, dict):
            parts = ["%s%s: %s" % (inner, _scalar(str(k)), _encode(v, indent + 1, str(k)))
                     for k, v in value.items()]
            return "{\n" + ",\n".join(parts) + "\n" + pad + "}"
        parts = ["%s%s" % (inner, _encode(v, indent + 1, None)) for v in value]
        return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
    return _scalar(value)


def render(document: Dict[str, Any]) -> str:
    return _encode(document, 0, None) + "\n"


# ==========================================================================
# 6. Entry point
# ==========================================================================

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", default=None,
                        help="directory to write into (default: <repo>/data)")
    parser.add_argument("--check", action="store_true", help="validate only; do not write")
    args = parser.parse_args()

    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = args.out_dir or os.path.join(repo_root, "data")

    document = build_document()

    if FAILURES:
        print("gen_building_economy: %d failure(s), nothing written" % len(FAILURES),
              file=sys.stderr)
        for failure in FAILURES:
            print("  FAIL %s" % failure, file=sys.stderr)
        return 1

    text = render(document)
    path = os.path.join(out_dir, "building_economy.json")

    if args.check:
        if os.path.exists(path):
            with open(path, encoding="utf-8") as handle:
                if handle.read() != text:
                    print("gen_building_economy: %s differs from the generated document" % path,
                          file=sys.stderr)
                    return 1
        print("gen_building_economy: all checks pass (--check, nothing written)")
        return 0

    os.makedirs(out_dir, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)

    overrides = document["generated"]["published_cell_overrides"]
    print("gen_building_economy: wrote %s" % path)
    print("  %d archetypes (%d of them six-level) = %d rows, grown from doc 03 s2.2's"
          " money table" % (len(ARCHETYPE_ORDER), len(SIXTH_LEVEL_ARCHETYPES),
                            sum(levels_of(a) for a in ARCHETYPE_ORDER)))
    print("  starter anchor: $%d/gh (18 house + 5 store + 3 apartment + 1 office, all L1)"
          % document["generated"]["starter_anchor"]["gross_base_tax_per_hour"])
    print("  %d published cell(s) that the curve does not reproduce exactly:" % len(overrides))
    for override in overrides:
        published = override["published"]
        curve = override.get("from_curve", override.get("from_closed_form"))
        print("    %-16s L%d %-22s published %-8s curve %-8s"
              % (override["archetype"], override["level"], override["field"], published, curve))
    return 0


if __name__ == "__main__":
    sys.exit(main())
